name: Godot

on:
  push:
    branches: [ "master" ]
    paths: 
      - Game/**
  pull_request:
    branches: [ "master" ]
    paths: 
      - Game/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      
      - name: Check GD Files
        run: .github/scripts/godotcheck.sh
